import os
from dotenv import load_dotenv

load_dotenv()

ACCESS_CONTROL_ALLOW_ORIGINS = os.getenv("ACCESS_CONTROL_ALLOW_ORIGINS")
ACCESS_CONTROL_ALLOW_HEADERS = os.getenv("ACCESS_CONTROL_ALLOW_HEADERS")
ACCESS_CONTROL_ALLOW_METHODS = os.getenv("ACCESS_CONTROL_ALLOW_METHODS")
